# Generated by Django 3.2.16 on 2023-03-13 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='allotted_time',
            field=models.FloatField(help_text='Enter in minutes.', validators=[django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
