# Generated by Django 3.2.16 on 2023-03-14 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20230314_0018'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variant',
            name='unique_question_is_correct_variant',
        ),
        migrations.AddField(
            model_name='studentwronganswer',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='studentwronganswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII')]),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='studentwronganswer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('text', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('text', 'question')},
        ),
    ]
